version: "3"

volumes:
  postgres_data: {}
  pgadmin_data: {}

services:
  flask:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  postgres:
    image: postgres:alpine
    container_name: postgres
    networks:
        - default
    env_file:
      - ./.envs/postgres.env
    ports:
        - 5432:5432
    restart: on-failure:5
    volumes:
        - postgres_data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
        - default
    env_file:
      - ./.envs/pgadmin.env
    ports:
        - 5050:80
    logging:
      driver: none
    restart: on-failure:5