"""empty message

Revision ID: 7c07768d0e10
Revises: 7208290cd90d
Create Date: 2022-07-12 13:23:58.604406

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "7c07768d0e10"
down_revision = "7208290cd90d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("sex", sa.String(length=100), nullable=False))
    op.create_unique_constraint(op.f("uq_user_id"), "user", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_id"), "user", type_="unique")
    op.drop_column("user", "sex")
    # ### end Alembic commands ###
